<script setup>
import { onMounted, ref, computed } from 'vue';
import axios from 'axios';
import AdminLayout from '../AdminLayout.vue';
const payload = ref({ Employees: [], Users: [] }), loading = ref(true), error = ref(''), query = ref('');
const employees = computed(() => (payload.value.Employees || []).filter(item => `${item.name} ${item.email} ${item.government_entity?.name || ''}`.toLowerCase().includes(query.value.toLowerCase())));
async function load() { try { const response = await axios.get('/admin/employees'); payload.value = response.data?.data || payload.value; } catch (e) { error.value = 'تعذر تحميل بيانات الموظفين.'; } finally { loading.value = false; } }
onMounted(load);
</script>
<template><AdminLayout page-title="الموظفون"><section class="head"><div><p class="eyebrow">إدارة فرق العمل</p><h2>الموظفون</h2><p class="muted">متابعة الموظفين المرتبطين بالجهات الحكومية.</p></div><span class="badge">{{ employees.length }} موظف</span></section><div v-if="error" class="alert">{{ error }}</div><section class="panel"><div class="toolbar"><input v-model="query" placeholder="ابحث باسم الموظف أو الجهة..." /></div><div v-if="loading" class="empty">جاري التحميل...</div><div v-else-if="!employees.length" class="empty">لا توجد نتائج.</div><div v-else class="grid"><article v-for="employee in employees" :key="employee.id" class="employee"><div class="avatar">{{ employee.name?.charAt(0) || 'م' }}</div><div><strong>{{ employee.name }}</strong><small>{{ employee.email }}</small><span>{{ employee.government_entity?.name || 'غير مرتبطة بجهة' }}</span></div></article></div></section></AdminLayout></template>
<style scoped>.head,.toolbar{display:flex;align-items:center}.head{justify-content:space-between;margin-bottom:1.4rem}.eyebrow{margin:0 0 .3rem;color:#d6aa50;font-size:.72rem;font-weight:700}.head h2{margin:0;color:#fff;font-size:1.45rem}.muted{margin:.45rem 0 0;color:rgba(255,255,255,.45);font-size:.8rem}.badge{color:#e3bd68;background:rgba(214,170,80,.12);padding:.55rem .8rem;border-radius:8px;font-size:.75rem}.panel{padding:1rem;background:rgba(255,255,255,.045);border:1px solid rgba(255,255,255,.08);border-radius:12px}.toolbar{margin-bottom:1rem}.toolbar input{width:100%;padding:.75rem 1rem;background:rgba(0,0,0,.13);border:1px solid rgba(255,255,255,.08);border-radius:8px;color:#fff;outline:0;font:inherit;font-size:.78rem}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:.8rem}.employee{display:flex;gap:.7rem;padding:1rem;background:rgba(255,255,255,.035);border-radius:10px}.avatar{display:grid;place-items:center;flex:none;width:38px;height:38px;background:linear-gradient(135deg,#1a4a8a,#d4a843);border-radius:50%;color:#fff;font-weight:700}.employee strong,.employee small,.employee span{display:block}.employee strong{color:#fff;font-size:.8rem}.employee small{color:rgba(255,255,255,.4);font-size:.68rem;margin:.25rem 0}.employee span{color:#d6aa50;font-size:.68rem}.empty{text-align:center;padding:3rem;color:rgba(255,255,255,.4);font-size:.8rem}.alert{padding:.8rem;background:rgba(248,113,113,.1);color:#fca5a5;border-radius:8px;margin-bottom:1rem;font-size:.78rem}@media(max-width:850px){.grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:560px){.grid{grid-template-columns:1fr}.head{align-items:flex-start;gap:1rem;flex-direction:column}}</style>
