<script setup>
import { ref } from 'vue';
import axios from 'axios';
import AdminLayout from './AdminLayout.vue';
const month = ref(new Date().toISOString().slice(0, 7)), loading = ref(''), message = ref('');
async function exportReport(type) { loading.value = type; message.value = ''; try { const response = await axios.get(`/admin/reports/monthly/${type}`, { params: { month: month.value } }); const url = response.data?.url || response.data?.data?.url; if (url) window.open(url, '_blank'); message.value = 'تم إنشاء التقرير بنجاح.'; } catch (e) { message.value = 'تعذر إنشاء التقرير حالياً.'; } finally { loading.value = ''; } }
</script>
<template><AdminLayout page-title="التقارير"><section class="head"><div><p class="eyebrow">تحليل الأداء</p><h2>التقارير</h2><p class="muted">صدّر ملخصاً شهرياً للشكاوى بصيغة مناسبة للمشاركة والأرشفة.</p></div></section><section class="report-card"><div class="report-icon">▤</div><div class="report-copy"><h3>تقرير الشكاوى الشهري</h3><p>اختر الشهر ثم حمّل التقرير بصيغة CSV أو PDF.</p><label>الشهر<input v-model="month" type="month" /></label><div class="actions"><button @click="exportReport('csv')" :disabled="!!loading">{{ loading === 'csv' ? 'جاري الإنشاء...' : 'تصدير CSV' }}</button><button class="secondary" @click="exportReport('pdf')" :disabled="!!loading">{{ loading === 'pdf' ? 'جاري الإنشاء...' : 'تصدير PDF' }}</button></div><p v-if="message" class="message">{{ message }}</p></div></section></AdminLayout></template>
<style scoped>.head{margin-bottom:1.4rem}.eyebrow{margin:0 0 .3rem;color:#d6aa50;font-size:.72rem;font-weight:700}.head h2{margin:0;color:#fff;font-size:1.45rem}.muted{margin:.45rem 0 0;color:rgba(255,255,255,.45);font-size:.8rem}.report-card{display:flex;gap:1rem;max-width:680px;padding:1.5rem;background:rgba(255,255,255,.045);border:1px solid rgba(255,255,255,.08);border-radius:13px}.report-icon{display:grid;place-items:center;width:48px;height:48px;flex:none;border-radius:12px;background:rgba(214,170,80,.13);color:#e3bd68;font-size:1.4rem}.report-copy h3{margin:0;color:#fff;font-size:1rem}.report-copy>p{color:rgba(255,255,255,.45);font-size:.78rem}.report-copy label{display:block;margin:1.2rem 0 .9rem;color:rgba(255,255,255,.5);font-size:.72rem}.report-copy input{display:block;margin-top:.4rem;padding:.65rem;background:#122952;border:1px solid rgba(255,255,255,.1);border-radius:8px;color:#fff}.actions{display:flex;gap:.6rem}.actions button{padding:.7rem 1rem;border:0;border-radius:8px;background:#d6aa50;color:#0a1c42;font-weight:700;cursor:pointer;font:inherit;font-size:.75rem}.actions button.secondary{background:rgba(255,255,255,.09);color:#fff}.actions button:disabled{opacity:.5;cursor:not-allowed}.message{color:#6ee7b7!important;font-size:.75rem!important}@media(max-width:550px){.report-card{flex-direction:column}.actions{flex-direction:column}.actions button{width:100%}}</style>
